config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  get 'errors/not_found'

  get 'errors/internal_server_error'

  root to: 'home#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: { :omniauth_callbacks => "users/omniauth_callbacks",
                                    :registrations => 'users/registrations' }
  begin
    ActiveAdmin.routes(self)
  rescue Exception => e
    puts "ActiveAdmin: #{e.class}: #{e}"
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  namespace :home, path: '/' do
    get :about
    get :become_guide
    get :partners
    get :term_of_services, path: 'term-of-services'
    get :privacy_policy, path: 'privacy-policy'
    get :copyright
    get :contact_us
    post :send_contact
    get :help
    get :example
    get :founders
    get :how_it_works, path: 'how-it-works'
    get :safety
    get :careers
    get :blog
  end

  resources :search, only: [:index, :create] do
  end

  resources :tours, path: 'tours' do
    member do
      get :profile
      put :update_profile, path: 'profile'
      patch :update_profile, path: 'profile'
      get :tour_itinerary
      put :update_tour_itinerary, path: 'tour_itinerary'
      get :additional_info
      put :update_additional_info, path: 'additional_info'
      get :preview
      put :update_preview, path: 'preview'
    end
    resources :reservations do
      member do
        get :passenger
        get :billing_information
        get :review_and_submit
      end
    end
  end

  resources :users, only: [:show, :update] do
    member do
      get :public_profile
    end
  end

  resources :users, only: [:index], path: '/manage/profile' do
    collection do
      get :host, path: 'guide'
      post 'become_guide' => 'hosts#create', :as => 'become_guide'
      get :references
      get :reservations
      get :travels
      get :crafted_tours
      get :verifications
      get :account_settings
      get :profile_information
      get :availability
      get :bank_accounts
      resources :bank_accounts, only: [:create, :update]
    end
  end

  namespace :users, path: '/manage/profile' do
    devise_scope :user do
      resources :references, only: [] do
        collection do
          post :email
          post :facebook
          post :twitter
          post :google_plus
        end
      end
    end
  end

  resources :messages

  resources :countries do
    resources :cities, only: [:show]
  end

  resources :subscribers, only: [:create]
end

app/models/concerns/user/private.rb
module User::Private
  extend ActiveSupport::Concern
  include JsonField

  included do
    before_validation :add_slug_if_not_assigned, on: :create
    before_validation :update_json_field
    after_validation :generate_invite_code, on: :create
  end

  private

  def add_slug_if_not_assigned
    self.username = (first_name && last_name) ? "#{first_name}_#{last_name}".downcase : "#{self.email[/^[^@]+/]}_#{Devise.friendly_token}"
  end

  def generate_invite_code
    self.invite_code = SecureRandom.uuid
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  DEFAULT_NAME = "Tourmega Lovers"
  DEFAULT_AVATAR_URL = Figaro.env.DEFAULT_AVATAR_URL
  GENDERS = ["Male", "Female"]
  GUIDE_TYPE = [  :licensed_tour_company,
                  :licensed_local_guide,
                  :unlicensed_local_guide
                ]

  devise :database_authenticatable, :registerable, :recoverable, :async,
         :rememberable, :trackable, :validatable, :lockable, :omniauthable, :omniauth_providers => [:facebook, :twitter]

  include Private
  # extend FriendlyId
  # friendly_id :username, use: :slugged

  has_many :verifications, dependent: :destroy
  has_one :host, dependent: :destroy
  has_many :tours
  has_many :active_tours, -> { where(visible: true) }, foreign_key: 'user_id', class_name: "Tour"
  belongs_to :primary_address, class_name: 'Location', foreign_key: :primary_address_id, dependent: :destroy
  belongs_to :nationality, class_name: 'Country', foreign_key: :nationality_id
  has_many :reservations, dependent: :destroy
  has_many :bank_accounts, dependent: :destroy

  enum guide_type: GUIDE_TYPE
  accepts_nested_attributes_for :host

  mount_uploader :avatar, AvatarUploader

  # validates :slug, presence: true, uniqueness: true
  validates :first_name, :last_name, presence: true

  class << self
    def collection
      select(:first_name, :last_name, :id).map{ |user| [user.first_name.to_s + ' ' + user.last_name.to_s, user.id] }
    end

    def from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        case auth.provider
        when 'facebook'
          user.email = auth.info.email
        when 'twitter'
          user.email = auth.info.nickname.concat('@twitter.com')
        end
        user.first_name = auth.info.name.split(' ')[0..-2].join(' ')
        user.last_name = auth.info.name.split(' ').last
        user.password = Devise.friendly_token[0, 20]
        user.remote_avatar_url = auth.info.image
      end
    end

    def import_from_external(user_json, provider)
      where(provider: provider, uid: user_json['id'].to_s).first_or_create do |user|
        user.email = "#{user_json['username']}@tournative.com"
        user.username = "#{provider}-#{user_json['username']}"
        user.first_name = user_json['full_name'].split(' ')[0..-2].join(' ')
        user.last_name = user_json['full_name'].split(' ').last
        user.remote_avatar_url = user_json['avatar']
        user.password = Devise.friendly_token[0, 20]
      end
      user = User.find_by(email: "#{user_json['username']}@tournative.com")

      filepath = "db/csv/#{Date.today.to_formatted_s(:number)}_users.csv"
      CSV.open(filepath, 'a+') do |csv|
        row = [ user.email, user.username, user.first_name, user.last_name, user.remote_avatar_url, user.provider, user.uid ]
        csv << row
      end
      user
    end
  end


  def name
    "#{first_name} #{last_name}".presence || email.presence || "Unidentifier"
  end

  def is_a_host?
    host.present?
  end

  def own_tour?(tour_id)
    tours.find(tour_id).present?
  end

  def verified?
    verifications.where(source: Verification::SOURCES, verified: true).size == Verification::SOURCES.size
  end

  Verification::SOURCES.each do |source|
    define_method "#{source}_verified?" do
      verifications.find_by(source: source).try(:verified)
    end
  end

  def total_reviews
    tours.inject(0){ |sum, tour| sum + tour.no_of_reviews }
  end

  def all_reviews
    TourReview.where(tour_id: tour_ids)
  end

  def total_references
    BookingReference.where(referral_code: self.invite_code).count
  end

  def current_bank_account
    bank_accounts.order('created_at ASC').first
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      flash[:alert] = "Cannot sign in with your Facebook"
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      flash[:alert] = "Cannot sign in with your Twitter"
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/references_controller.rb
class Users::ReferencesController < Devise::RegistrationsController
  before_action :authenticate_user!
  before_action :set_navigation

  def facebook
  end

  def twitter
  end

  def google_plus
  end

  def email
  end

  private

  def reference_params
    params.permit(:reference_email)
  end

  def set_navigation
    flash.now[:notice] = t('references.successfully')
    render 'referral.js'
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def update
    if current_user.update_attributes(password: user_params[:password], password_confirmation: user_params[:password_confirmation])
      sign_in(current_user, bypass: true)
      redirect_to users_path
      flash[:notice] = "Update password successfully"
    else
      redirect_to users_path
      flash[:error] = "New password is not acceptable"
    end
  end

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:public_profile]
  before_action :fetch_reservations, only: [:reservations]
  before_action :fetch_travels, only: [:travels]
  before_action :fetch_crafted_tours, only: [:crafted_tours]
  before_action :get_public_user_tours, only: [:public_profile]
  before_action :set_bank_account, only: [:bank_accounts]
  before_action :set_column_navigation, only: [:reservations, :travels, :references, :verifications, :crafted_tours, :account_settings, :profile_information, :availability, :bank_accounts]

  def public_profile
    @reviews = TourReview.for_user(@user.id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def crafted_tours; end
  def reservations; end
  def travels; end
  def verifications; end
  def account_settings; end
  def profile_information; end
  def availability; end
  def references; end
  def bank_accounts; end

  def index
    @column = 'profile'

    respond_to do |format|
      format.html
      format.js { render 'content.js' }
    end
  end

  def update
    @column = 'profile'
    flash.now[:notice] = "Update profile successfully" if current_user.update(user_params)

    respond_to do |format|
      format.html { redirect_to users_path }
      format.js { render 'content.js' }
    end
  end

  def host
    @host = current_user.host || current_user.build_host
  end

  private

  def set_column_navigation
    @column = action_name
    respond_to do |format|
      format.html { render 'index.html' }
      format.js { render 'content.js' }
    end
  end

  def user_params
    params.require(:user).permit(:gender, :phone, :job_title, :biography, :date_of_birth, :hobbies, :guide_type, :nationality_id, :primary_address_id, :email, :first_name, :last_name, :avatar)
  end

  def fetch_reservations
    if params[:status] == 'confirmed'
      @reservations = current_user.reservations.completed
    else
      @reservations = current_user.reservations.pending
    end
    @reservations.includes(:tour)
  end

  def fetch_travels
    @reservations = current_user.reservations.completed
    @travels = @reservations.for_tours
  end

  def fetch_crafted_tours
    @tours = current_user.tours.page(params[:page]).per(6)
  end

  def get_public_user_tours
    @user = User.find(params[:id])
    @tours = @user.tours
  end

  def set_bank_account
    @bank_account = current_user.current_bank_account || current_user.bank_accounts.new
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_verified_status(user, source)
    if user.send("#{source}_verified?")
      (source == :phone_number) ? user.phone.mask_all_except_last_numbers(2,'▒') : "Verified"
    else
      "Not Verified"
    end
  end

  def display_signed_up_time(user)
    "Member since #{user.created_at.strftime('%B %Y')}"
  end

end

app/views/users/_content_account_settings.html.haml
.row
  .small-12.columns
    = render 'profile_navbar'

#profile
  .row
    .small-12.medium-7.columns
      %h4.manage-header Change Password
      .change-password.space-top
        = simple_form_for(current_user, as: :user, url: user_registration_path(current_user), method: :put, html: { class: 'ng-pristine ng-valid' }) do |f|
          = f.input :email, id: 'traveler_email', required: true, input_html: { disabled: true }
          = f.input :password, autocomplete: 'off', label: 'New Password'
          = f.input :password_confirmation
          .text-right
            = f.button :submit, 'Update Password', 'data-disable-with' => 'Updating', class: 'button expand'

:javascript
  $(function(){
    $('.content-column').removeClass('free-meals');
    $('li.profile>a').addClass('current');
  });

app/views/users/_content_availability.html.haml
.row
  .small-12.columns
    = render 'profile_navbar'

#profile
  .row
    .small-12.medium-7.columns
      %h4.manage-header Availability
      .space-top

:javascript
  $(function(){
    $('.content-column').removeClass('free-meals');
    $('li.availability>a').addClass('current');
    $('li.profile>a').addClass('current');
  });

app/views/users/_content_pending_reservations.html.haml
.row
  .small-12.columns
    %ul.breadcrumbs
      %li
        = link_to "#{current_user.name}", users_path, remote: true
      %li.unavailable
        %a{:href => "#"} Pending Reservations
.row.overflow-scroll-x
  = render 'reservation_table', reservations: @reservations

:javascript
  $(function(){
    $('.content-column').removeClass('free-meals');
    $('li.pending-reservations>a').addClass('current');
  });

app/views/users/_content_profile.html.haml
.row
  .small-12.columns
    = render 'profile_navbar'

#profile
  = simple_form_for(current_user, url: user_path(current_user.id), method: :put, remote: true, html: { class: 'ng-pristine ng-valid' }) do |f|
    .row
      .small-12.medium-7.columns
        %h4.manage-header Traveler Information
        = f.input :first_name, required: true
        = f.input :last_name, required: true
        = f.input :biography, as: :text, input_html: { rows: 10, type: 'text', placeholder: 'From 50 to 500 characters that describes yourself the best' }
        .text-right
          = link_to 'View Your Profile', public_profile_user_path(current_user), target: '_blank', class: 'button btn btn-default'
          = f.button :submit, 'Update Profile', 'data-disable-with' => 'Updating', class: 'button'
      .small-12.medium-5.columns
        %h4.manage-header Profile Avatar
        .row
          .small-12.medium-6.columns.user-info.text-center
            .vertical-align
              = f.input :avatar, as: :file, input_html: { accept: "image/png,image/gif,image/jpeg", class: 'hidden'}, label: 'Change Avatar'
          .small-12.medium-6.columns.user-info.text-center
            .vertical-align
              = image_tag f.object.avatar_url, alt: f.object.name, class: 'avatar large'
          .small-12.columns.text-center.hidden
            %img{:src => "", id: 'temporary-avatar', width: '300px', height:'300px', style: 'margin-bottom: 20px;' }
            .form-group
              %label.string{style: 'padding-left: 60px; background: url(https://d26oxw2p26xsun.cloudfront.net/assets/icons/arrow-d2479cd3c113adea5dca195ae630c8bd.png) no-repeat;'} Click update to change

:javascript
  $(function(){
    $('.vertical-align:has(img)').on('click', function(){
      $('#user_avatar').click();
    });

    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $('#temporary-avatar').attr('src', e.target.result).attr('alt', 'Temporary Avatar').removeClass('hidden');
          $('#temporary-avatar').parent().removeClass('hidden');
        }
        reader.readAsDataURL(input.files[0]);
      }
    }

    $('#user_avatar').on('change', function(){
      readURL(this);
    });
    $('.content-column').removeClass('free-meals');
    $('li.profile>a').addClass('current');
  });

app/views/users/_content_profile_information.html.haml
.row
  .small-12.columns
    = render 'profile_navbar'

= javascript_include_tag 'gmap_autocomplete'

#profile
  = simple_form_for(current_user, url: user_path(current_user.id), method: :put, remote: true, html: { class: 'ng-pristine ng-valid' }) do |f|
    .row
      .small-12.medium-7.columns
        %h4.manage-header Personal
        = f.input :gender, as: :select, collection: User::GENDERS, required: true
        = f.input :phone_number, input_html: { placeholder: 'E.g. (+1) 322-454-3495' }
        = f.input :job_title, label: "Current occupation", input_html: { placeholder: 'Title' }
        = f.label 'Birthdate'
        = f.text_field :date_of_birth, class: 'form-control datepicker', placeholder: 'mm/dd/yyyy', label: 'Birth date'
        = f.input :hobbies, as: :text, input_html: { rows: 10, type: 'text', placeholder: 'From 50 to 250 characters that describes your hobbies the best' }
        .text-right
          = f.button :submit, 'Update Profile', 'data-disable-with' => 'Updating', class: 'button'
      .small-12.medium-5.columns
        %h4.manage-header Additional
        .row
          .small-12.columns.user-info
            = f.input :guide_type, as: :select, collection: User::GUIDE_TYPE.map{|e| [e.to_s.humanize, e]}
            = f.input :primary_address, as: :fake, input_html: { name: 'user[primary_address]', id: 'user_primary_address', class: 'hidden', value: f.object.primary_address.try(:hash_attributes) }, label: false, wrapper: false, required: false
            = f.input :locate_primary_address, as: :fake, input_html: { placeholder: 'Choose your current primary address', class: 'autocomplete-location', autocomplete: 'off', 'fill-to-input' => 'user_primary_address', value: f.object.primary_address.try(:address) }, label: 'Primary address'
            = f.input :languages, as: :select, collection: Tour::LANGUAGES, :input_html => { :class => "chosen-input with-bootstrap", multiple: true, 'data-placeholder' => "Choose a languages..." }, include_hidden: false, label: 'Languages'
            = f.input :nationality_id, as: :select, collection: Country.collection, :input_html => { :class => "chosen-input with-bootstrap", multiple: false }

:javascript
  loadGoogleMapScript('#{google_map_uri}', true, initAutocomplete);
  $(function(){
    $('.chosen-input').chosen({no_results_text: "No country match", placeholder_text_single: "Choose a country", allow_single_deselect: true, search_contains: true});
    $('.content-column').removeClass('free-meals');
    $('li.profile>a').addClass('current');
  });

app/views/users/_content_reservations.html.haml
.row
  .small-12.columns
    %ul.breadcrumbs
      %li.unavailable
        = link_to "Reservations", reservations_users_path, remote: true

.row.overflow-scroll-x
  = render 'reservation_table', reservations: @reservations

:javascript
  $(function(){
    $('.content-column').removeClass('free-meals');
    $('li.reservations>a').addClass('current');
  });

app/views/users/_panel_about_me.html.haml
.panel.panel-has-header.white-bg
  .panel-header About Me
  .panel-body
    %p= user.biography

app/views/users/_public_profile_tours.html.haml
.small-12.column
  .listings-container.flexslider
    %ul.slides
      - tours.each do |similar_tour|
        %li
          .item
            .panel-image.listing-img
              .media-photo
                %a{:href => "#{tour_path(similar_tour)}"}
                  %img{:src => "#{similar_tour.images.first.try(:url)}"}/

              %a.panel-overlay-bottom-left.panel-overlay-listing-price{:href => "#"}
                .price-container
                  %sup $
                  %span.price-amount= similar_tour.price
                %span.icon-instant-book.glyphicon.glyphicon-flash
            .panel-body.panel-card-section
              .info
                %a.profile-picture{:href => "#{public_profile_user_path(similar_tour.creator)}"}
                  %img{:alt => "name", :src => "#{similar_tour.creator_avatar_url}"}/
                %h3.listing-name{:title => "#{similar_tour.name}"}
                  %a{:href => "#{tour_path(similar_tour)}"}= similar_tour.name
                .listing-location
                  = render 'shared/tour_rating', tour: similar_tour

app/views/users/_references_box.html.haml
.space-4#references.references
  %h2.block-title
    References
    %small= "(#{user.total_references})"
  .references-list
    .row.text-center-sm.item
      .col-xs-12.col-sm-4.col-lg-2
        .avatar-wrapper.text-center
          .media-photo.media-round
            %a{:href => "#", :title => "Peter"}
              %img{:src => "/uploads/tour/images/199/533f11a0-c234-4530-8217-1ec5f14d9c5f.jpg"}
          .profile-name
            %a{:href => "#", :title => "Peter"} Peter
      .col-xs-12.col-sm-8.col-lg-10
        .comment-container
          I have known James for over 10 years. I have stayed at his properties both in London and in Spain and can highly recommend him as Airbnb host and his fantastic homes.
        .date.text-gray
          August 2012
        .relationship.text-right
          Peter is a Friend
    .row.line-separation
      .col-xs-12.col-sm-4.col-lg-2
      .col-xs-12.col-sm-8.col-lg-10
        %hr

app/views/users/_wishlist_box.html.haml
.space-6
  .block.block-wishlist
    .block-title
      Wishlist
      %small (3)
    .block-content
      .row
        .col-sm-4
          .media-photo.wishlist-item
            .media-cover.text-center.media-cover-dark
              %a{:href => "#", :title => "Holiday Places"}
                %img{:src => "/uploads/country/scene_images/174/small_philippines.jpg"}
            .row-table.media-caption
              .small-12.column.col-middle.text-center
                %h2 Holiday Places
                %a.button.btn-guest{:href => "#", :title => "11 Listings"} 11 Listings
        .col-sm-4
          .media-photo.wishlist-item
            .media-cover.text-center.media-cover-dark
              %a{:href => "#", :title => "New York"}
                %img{:src => "/uploads/country/scene_images/124/small_laos.jpg"}
            .row-table.media-caption
              .small-12.column.col-middle.text-center
                %h2 New York
                %a.button.btn-guest{:href => "#", :title => "11 Listings"} 3 Listings
        .col-sm-4
          .media-photo.wishlist-item
            .media-cover.text-center.media-cover-dark
              %a{:href => "#", :title => "Spain"}
                %img{:src => "/uploads/country/scene_images/19/small_bangladesh.jpg"}
            .row-table.media-caption
              .small-12.column.col-middle.text-center
                %h2 Spain
                %a.button.btn-guest{:href => "#", :title => "11 Listings"} 5 Listings

app/views/users/content.js.erb
$(function(){
  $('#profile_content').html("<%= j render('content_' + @column)%>");
  $('li>a').removeClass('current');
  $('.current-user-avatar').attr('src', "<%= current_user.avatar_url%>");
});

<%= render 'shared/flash_now_messages' %>

app/views/users/index.html.haml
= javascript_include_tag 'history_state', media: 'all'

%section.main-section.white-bg.no-margin-top
  .row.wide
    .small-12.medium-4.xlarge-3.columns.sidebar-column.light-grey-bg{:style => "height: 600px;"}
      #manage_sidebar
        .row
          .small-12.large-3.columns.text-center.user-info.flush-left
            .vertical-align
              %img.avatar.current-user-avatar.large{:alt => "#{current_user.name}", :src => "#{current_user.avatar_url}"}
          .small-12.large-9.columns.user-info
            .vertical-align
              %h4.border-bottom= current_user.name
              %span.small= current_user.email
        = render "manage_sidebar"
    #profile_content.columns.content-column.medium-8.small-12.xlarge-9
      = render "content_#{@column}"

:javascript
  $(function(){
    $('body').removeClass().addClass('manage').attr('style','');
    $('#header').addClass('solid');
  });

app/views/users/manage_calendar.html.haml
= javascript_include_tag 'history_state', media: 'all'

%section.main-section
  .manage-listing
    .manage-listing-content-wrapper.row
      .manage-listing-content.white-bg
        %h4 Select an options:
        .cols-set-options.cols-3-set
          .col-1.col-option.text-center.calendar-option.calendar-always
            .col-content
              .media-photo
                %img{:alt => "Always", :src => "#{asset_url('calendar-always.png')}"}
              %h5 Always Available
              %strong List completely open calendar
          .col-2.col-option.text-center.calendar-option.calendar-onetime
            .col-content
              .media-photo
                %img{:alt => "Onetime", :src => "#{asset_url('calendar-onetime.png')}"}
              %h5 Onetime Available
              %strong List some days as available
          .col-3.col-option.expand-onetime
            .col-content
              %h5 Start Date
              %input.checkin.ui-datepicker{:type => "text", :name =>"start-date", :placeholder => "Start date"}
              %h5 End Date
              %input.checkout.ui-datepicker{:type => "text", :name =>"end-date", :placeholder => "End date"}
    .manage-listing-nav.light-grey-bg
      .nav-sections
        .row
          .small-12.column
            .block.block-listing-nav
              .block-title Basics
              .block-content
                %ul.list-unstyled
                  %li.active
                    %a{:href => "#"} Calendar
                  %li
                    %a{:href => "#"} Pricing
            .block.block-listing-nav
              .block-title Description
              .block-content
                %ul.list-unstyled
                  %li
                    %a{:href => "#"} Overview
                  %li
                    %a{:href => "#"} Photos
            .block.block-listing-nav
              .block-title Settings
              .block-content
                %ul.list-unstyled
                  %li
                    %a{:href => "#"} Amenities
                  %li
                    %a{:href => "#"} Listing
      .publish-actions.text-center
        Complete 
        %strong.color-red 6 steps
        to list your space

:javascript
  $(function(){
    $('.ui-datepicker').datepicker({
      format: 'dd/mm/yyyy',
      todayHighlight: true,
      leftArrow: '&laquo;',
      rightArrow: '&raquo;',
      autoclose: true
    });
    $('.calendar-option').on('click', function(){
      $('.calendar-option').removeClass('selected');
      $(this).addClass('selected');
      var expandOnetime = $(this).parent().find('.expand-onetime');
      if($(this).hasClass('calendar-onetime')){
        expandOnetime.show();
      }else{
        expandOnetime.hide();
      }
    });
    $('body').removeClass().addClass('manage').attr('style','');
    $('#header').addClass('solid');
  });

app/views/users/public_profile.html.haml
= javascript_include_tag 'history_state', media: 'all'

- content_for(:title, "#{@user.name} on Tourmega")

%section.main-section.no-margin-top
  .public-profile
    .row
      .col-xs-12.col-sm-4.col-md-3
        .block.block-profile-media
          %img{:src => @user.avatar_url}
        = render 'panel_verification', user: @user
        = render 'panel_about_me', user: @user

      .col-xs-12.col-sm-8.col-md-9
        %h1= "Hey, I’m #{@user.name}"
        %h5
          - if @user.primary_address
            %a= @user.primary_address.address
            %br/
          %span= display_signed_up_time(@user)
        .space-6
          %p= @user.biography
        .space-6
          - if @tours.present?
            .block.block-listings
              .block-title
                Tours
                %small= "(#{@tours.count})"
              .block-content
                = render 'public_profile_tours', tours: @tours
        .space-6
          .user-badge
            .badge-item
              %a{:href => "#", :title => "Reviews"}
                %span.count= @user.total_reviews
                %span.text Reviews
            .badge-item
              %a{:href => "#references", :title => "Reference"}
                %span.count= @user.total_references
                %span.text Reference
            .badge-item.verified-item{"data-toggle" => "tooltip"}
              - if @user.verified?
                %a{:href => "#", :title => "Verified"}
                  %i.icon.fa.fa-check-square-o
                  %span.text Verified
                  #verified-info
                    .panel-header Verified ID
                    .panel-body
                      %p= "#{@user.name} has completed online and offline ID verification."
              - else
                %a{:href => "#", :title => "Not Verified"}
                  %i.icon.red.fa.fa-times-circle-o
                  %span.text Not Verified

        - if false
          = render 'wishlist_box', user: @user
        = render 'reviews_box', user: @user

:javascript
  $(function(){
    $('body').removeClass().addClass('manage').attr('style','');
    $('#header').addClass('solid');
  });